
export default (http, store) => {

  // https://github.com/mzabriskie/axios#interceptors
  http.interceptors.request.use((config) => {
    store.dispatch('setFetching', true);
    return config;
  }, (error) => {
    // Do something with request error
    return Promise.reject(error);
  });
  http.interceptors.response.use(
    (response) => {
      store.dispatch('setFetching', false);

      return response;
    },
    /**
    * This is a central point to handle all
    * error messages generated by HTTP
    * requests
    */
    (error) => {
      const { response } = error;

      // console.log(response);
      store.dispatch('setFetching', false);

      // if ([401, 400].indexOf(response.status) > -1) {
      //   window.location = '/login';
      // }

      return Promise.reject(error);
    },
  );
};
